name: zip
on:
  push:
    branches:
      - main

env:
  VERSION: 1.0.2
  MINECRAFT_VERSION: 1.21.11
  NOTES: |
    - New Logo Art

jobs:
  zip-and-publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: 🫸Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: 'v${{ env.VERSION }}_${{ env.MINECRAFT_VERSION }}'
            release_name: '${{ github.event.repository.name }} v${{ env.VERSION }} ${{ env.MINECRAFT_VERSION }}'
            body: '${{ env.NOTES }}'

      - name: 🤐 Zipping SMP
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: SMP/
          dest: SMP.zip

      - name: ⬆️ Uploading SMP Release
        id: upload-SMP-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./SMP.zip
          asset_name: SMP++.zip
          asset_content_type: application/zip

      - name: 🤐 Zipping Hub
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: Hub/
          dest: Hub.zip

      - name: ⬆️ Uploading Hub Release
        id: upload-Hub-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Hub.zip
          asset_name: Hub++.zip
          asset_content_type: application/zip

      - name: ✅ Publishing release
        run: gh release edit "v${{ env.VERSION }}_${{ env.MINECRAFT_VERSION }}" --draft=false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
